FROM ubuntu:18.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update 
RUN apt-get install -y apt-utils
RUN apt-get install -y htop 
RUN apt-get install -y vim
RUN apt-get install -y nano
RUN apt-get install -y openssh-client
RUN apt-get install -y openssh-server

RUN apt-get install -y gcc
RUN apt-get install -y libopenmpi2 libopenmpi-dev

RUN useradd -ms /bin/bash student
USER student
WORKDIR /home/student/lab1/openmpi

ENTRYPOINT /bin/bash
